# Setup
title:        Brian's Other Website
tagline:      Welcome to my site!
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Brian Caffey
  url:        http://briancaffey.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
